### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by xfce** [MarcProe/LibrePilot.arduino#2]
Hi,
I download the file, and compiled ,but got an error, could you please help me, thanks
https://vgy.me/WjItsk.png

**Comment by MarcProe** [comment]
Looks like gcc no longer allows the default parameter definition both in the header, and in the cpp file (which sort of makes sense).

I'll fix that.

**Comment by MarcProe** [comment]
Fixed: 753f7fd56c5cd40fc10e7341151dd3e4f6fc374b
